# 2. Основы тензоров PyTorch

**Цель:** Изучить создание тензоров, операции, типы данных, устройства и автоматическое дифференцирование.

---

In [1]:
# Импортируем необходимые библиотеки
import os

import torch
import torch.nn.functional as F
import numpy as np


## 2.1 Создание тензоров

In [2]:
# Создание тензора из списка Python
t1 = torch.tensor([1, 2, 3, 4, 5])
print(f"From list: {t1}, shape={t1.shape}")

# Из numpy-массива: тензоры и numpy легко конвертируются друг в друга
t2 = torch.tensor(np.array([[1, 2], [3, 4]]))
print(f"From numpy:\n{t2}")

# Случайный тензор: torch.randn — нормальное распределение N(0,1)
t3 = torch.randn(2, 3)
print(f"Random normal:\n{t3}")

# Нули, единицы, единичная матрица — полезно для инициализации
t4 = torch.zeros(2, 4)
t5 = torch.ones(3, 3)
t6 = torch.eye(4)
print(f"Zeros:\n{t4}")
print(f"Ones:\n{t5}")
print(f"Identity:\n{t6}")

# torch.arange — аналог range, torch.linspace — равномерно распределённые точки
t7 = torch.arange(0, 10, 2)
t8 = torch.linspace(0, 1, 5)
print(f"Arange: {t7}")
print(f"Linspace: {t8}")

From list: tensor([1, 2, 3, 4, 5]), shape=torch.Size([5])
From numpy:
tensor([[1, 2],
        [3, 4]])
Random normal:
tensor([[-0.2479, -1.3262,  0.0087],
        [-1.9508,  0.7044,  0.1076]])
Zeros:
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
Ones:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
Identity:
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
Arange: tensor([0, 2, 4, 6, 8])
Linspace: tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


## 2.2 Типы данных (dtype) и устройства (device)

In [3]:
# Типы данных: тензоры могут хранить числа разных типов
float_t = torch.tensor([1.0, 2.0], dtype=torch.float32)  # 32-битное с плавающей точкой (стандарт)
double_t = torch.tensor([1.0, 2.0], dtype=torch.float64)  # 64-битное (больше точность)
int_t = torch.tensor([1, 2], dtype=torch.int64)           # целочисленный
print(f"float32: {float_t.dtype}")
print(f"float64: {double_t.dtype}")
print(f"int64: {int_t.dtype}")

# PyTorch по умолчанию создаёт тензоры с float32, если есть дробная часть
x = torch.tensor([1, 2, 3], dtype=torch.float32)
print(f"Default: {x.dtype}")

# Перемещение на устройство: CPU, CUDA (NVIDIA) или MPS (Apple)
if torch.cuda.is_available():
    device = torch.device("cuda")

elif torch.backends.mps.is_available():
    device = torch.device("mps")

else:
    device = torch.device("cpu")
t_gpu = torch.tensor([1, 2, 3], device=device)
print(f"On device: {t_gpu.device}")


float32: torch.float32
float64: torch.float64
int64: torch.int64
Default: torch.float32
On device: cuda:0


## 2.3 Индексация и срезы

In [4]:
# Индексация и срезы: работаем как с numpy или списками
x = torch.randn(4, 5)
print(f"Tensor 4x5:\n{x}\n")

# Обычная индексация: строка, столбец, подматрица
print(f"First row: {x[0]}")
print(f"First column: {x[:, 0]}")
print(f"Submatrix (1:3, 1:4):\n{x[1:3, 1:4]}")
print(f"Element (2, 3): {x[2, 3]}")

# Boolean indexing: выбираем элементы по условию
mask = x > 0
print(f"Positive values: {x[mask]}")
print(f"Number of positive: {mask.sum()}")

Tensor 4x5:
tensor([[-0.3703, -0.0255,  0.8105, -0.8670, -1.1698],
        [ 0.6426,  0.4911,  0.1906, -0.0200,  0.8094],
        [-0.5998,  1.6744,  0.5360,  0.2112, -0.3111],
        [ 1.3644,  0.8007,  1.0977,  0.8142,  1.3022]])

First row: tensor([-0.3703, -0.0255,  0.8105, -0.8670, -1.1698])
First column: tensor([-0.3703,  0.6426, -0.5998,  1.3644])
Submatrix (1:3, 1:4):
tensor([[ 0.4911,  0.1906, -0.0200],
        [ 1.6744,  0.5360,  0.2112]])
Element (2, 3): 0.21122117340564728
Positive values: tensor([0.8105, 0.6426, 0.4911, 0.1906, 0.8094, 1.6744, 0.5360, 0.2112, 1.3644,
        0.8007, 1.0977, 0.8142, 1.3022])
Number of positive: 13


## 2.4 Решейп и изменение формы

In [5]:
# Изменение формы тензора — важный навык для работы с батчами
x = torch.arange(12)
print(f"Original: {x.shape} -> {x}")

# view() — меняет форму без копирования данных (разделяет память с исходным тензором)
y = x.view(3, 4)
print(f"View (3,4):\n{y}")

# reshape() — то же самое, но безопаснее: копирует данные если view невозможен
z = x.reshape(2, 6)
print(f"Reshape (2,6):\n{z}")

# Flatten — превращает многомерный тензор в одномерный
w = torch.randn(2, 3, 4)
print(f"Flatten {w.shape} -> {w.flatten().shape}")

# Transpose — транспонирование матрицы
t = torch.randn(2, 3)
print(f"Transpose {t.shape} -> {t.T.shape}")

# Unsqueeze / squeeze — добавление / удаление размерности длины 1
a = torch.randn(3)
print(f"Unsqueeze {a.shape} -> {a.unsqueeze(0).shape} -> {a.unsqueeze(1).shape}")
b = torch.randn(1, 3, 1, 4)
print(f"Squeeze {b.shape} -> {b.squeeze().shape}")

Original: torch.Size([12]) -> tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
View (3,4):
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Reshape (2,6):
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
Flatten torch.Size([2, 3, 4]) -> torch.Size([24])
Transpose torch.Size([2, 3]) -> torch.Size([3, 2])
Unsqueeze torch.Size([3]) -> torch.Size([1, 3]) -> torch.Size([3, 1])
Squeeze torch.Size([1, 3, 1, 4]) -> torch.Size([3, 4])


## 2.5 Математические операции

In [6]:
# Поэлементные операции: +, -, *, /, ** работают как в numpy
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

print(f"a + b = {a + b}")
print(f"a - b = {a - b}")
print(f"a * b = {a * b}")  # поэлементное умножение, не матричное!
print(f"a / b = {a / b}")
print(f"a ** 2 = {a ** 2}")

# Матричное умножение: torch.mm или оператор @
A = torch.randn(3, 4)
B = torch.randn(4, 2)
C = torch.mm(A, B)  # или A @ B
C2 = A @ B
print(f"Matmul: {A.shape} @ {B.shape} = {C.shape}")

# Batch matmul: матричное умножение для батча матриц (batch, n, m) @ (batch, m, p)
batch_A = torch.randn(8, 3, 4)
batch_B = torch.randn(8, 4, 5)
batch_C = torch.bmm(batch_A, batch_B)
print(f"Batch matmul: {batch_C.shape}")

a + b = tensor([5., 7., 9.])
a - b = tensor([-3., -3., -3.])
a * b = tensor([ 4., 10., 18.])
a / b = tensor([0.2500, 0.4000, 0.5000])
a ** 2 = tensor([1., 4., 9.])
Matmul: torch.Size([3, 4]) @ torch.Size([4, 2]) = torch.Size([3, 2])
Batch matmul: torch.Size([8, 3, 5])


## 2.6 Broadcasting

In [7]:
# Broadcasting: автоматическое расширение размерностей для операций
x = torch.ones(3, 4)
y = x + 5  # скаляр 5 «растягивается» до размера (3,4)
print(f"Tensor + scalar:\n{y}")

# Разные формы: (3,1) + (4,) -> (3,4) — broadcasting вдоль обеих осей
a = torch.randn(3, 1)  # столбец
b = torch.randn(4)     # строка
c = a + b              # broadcasting: (3,1) + (4,) -> (3,4)
print(f"Broadcast {a.shape} + {b.shape} -> {c.shape}")

# Практика: нормализация батча вручную с помощью broadcasting
batch = torch.randn(16, 64)  # (batch, features)
mean = batch.mean(dim=0, keepdim=True)  # среднее по батчу -> (1, 64)
std = batch.std(dim=0, keepdim=True)    # стандартное отклонение -> (1, 64)
normalized = (batch - mean) / std  # broadcasting: (16,64) - (1,64) -> (16,64)
print(f"Manual batch norm: input {batch.shape}, output {normalized.shape}")
print(f"Normalized mean: {normalized.mean():.4f}, std: {normalized.std():.4f}")

Tensor + scalar:
tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])
Broadcast torch.Size([3, 1]) + torch.Size([4]) -> torch.Size([3, 4])
Manual batch norm: input torch.Size([16, 64]), output torch.Size([16, 64])
Normalized mean: -0.0000, std: 0.9687


## 2.7 Автоматическое дифференцирование (Autograd)

In [8]:
# Autograd: автоматическое дифференцирование — сердце обучения нейросетей
# requires_grad=True говорит PyTorch строить граф вычислений
x = torch.tensor([2.0, 3.0], requires_grad=True)
print(f"x: {x}, requires_grad: {x.requires_grad}")

# y = x^2 + 2x + 1 — каждый оператор добавляет узел в граф
y = x ** 2 + 2 * x + 1
print(f"y = x^2 + 2x + 1: {y}")

# sum() чтобы получить скаляр (backward работает только от скаляров)
z = y.sum()
print(f"z = sum(y): {z}")

# backward() вычисляет градиенты по всем requires_grad тензорам
z.backward()
# x.grad содержит dz/dx = dy/dx = 2x + 2 -> [2*2+2=6, 2*3+2=8]
print(f"dz/dx: {x.grad}")

x: tensor([2., 3.], requires_grad=True), requires_grad: True
y = x^2 + 2x + 1: tensor([ 9., 16.], grad_fn=<AddBackward0>)
z = sum(y): 25.0
dz/dx: tensor([6., 8.])


In [9]:
# Пример с двумя переменными: функция f(x,y) = x^2*y + y^3
x = torch.tensor(2.0, requires_grad=True)
y = torch.tensor(3.0, requires_grad=True)

f = x ** 2 * y + y ** 3
f.backward()  # считаем градиенты по x и y

print(f"x = {x.item()}, y = {y.item()}")
print(f"f(x,y) = x^2*y + y^3 = {f.item()}")
# Аналитически: df/dx = 2*x*y, df/dy = x^2 + 3*y^2
print(f"df/dx = 2*x*y = {x.grad.item():.2f} (expected: {2*2*3:.2f})")
print(f"df/dy = x^2 + 3*y^2 = {y.grad.item():.2f} (expected: {4 + 27:.2f})")

x = 2.0, y = 3.0
f(x,y) = x^2*y + y^3 = 39.0
df/dx = 2*x*y = 12.00 (expected: 12.00)
df/dy = x^2 + 3*y^2 = 31.00 (expected: 31.00)


In [10]:
# Демонстрация накопления градиентов — важный момент для обучения
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)

# Первый backward
loss = (x ** 2).sum()
loss.backward()
print(f"After first backward: {x.grad}")  # 2*x

# Градиенты накапливаются (суммируются) при повторном backward!
loss2 = (x * 2).sum()
loss2.backward()
print(f"After second backward (ACCUMULATED): {x.grad}")  # 2*x + 2

# Поэтому нужно обнулять градиенты перед каждым шагом обучения
x.grad.zero_()
print(f"After zero_(): {x.grad}")

After first backward: tensor([2., 4., 6.])
After second backward (ACCUMULATED): tensor([4., 6., 8.])
After zero_(): tensor([0., 0., 0.])


In [11]:
# detach() и torch.no_grad() — способы отключить градиенты
x = torch.tensor([2.0], requires_grad=True)

# detach() — отсоединяет тензор от графа вычислений
y = x ** 2
z = y.detach()  # z не требует градиента и не связан с x
w = z ** 2       # операции над z не отслеживаются
print(f"z.requires_grad: {z.requires_grad}")

# torch.no_grad() — контекстный менеджер, отключающий градиенты
# Используется для инференса и оценки модели
with torch.no_grad():
    y_no_grad = x ** 3
    print(f"y_no_grad.requires_grad: {y_no_grad.requires_grad}")

print("Detach and no_grad demonstrated")

z.requires_grad: False
y_no_grad.requires_grad: False
Detach and no_grad demonstrated


## 2.8 Функция потерь: MSE вручную vs torch

In [12]:
# Функция потерь MSE (Mean Squared Error): реализация вручную и через torch
pred = torch.tensor([2.5, 0.0, 1.2, -0.8], requires_grad=True)
target = torch.tensor([3.0, -0.5, 1.0, 0.0])

# MSE вручную: среднее квадратов разниц
mse_manual = ((pred - target) ** 2).mean()
print(f"MSE (manual): {mse_manual.item():.4f}")

# MSE через готовую функцию PyTorch
mse_torch = torch.nn.functional.mse_loss(pred, target)
print(f"MSE (torch):  {mse_torch.item():.4f}")

# Градиенты MSE по предсказаниям: d(MSE)/dpred = 2*(pred-target)/N
mse_manual.backward()
print(f"grad w.r.t pred: {pred.grad}")
print(f"grad formula: 2*(pred-target)/N = {2*(pred.data - target)/len(pred)}")

MSE (manual): 0.2950
MSE (torch):  0.2950
grad w.r.t pred: tensor([-0.2500,  0.2500,  0.1000, -0.4000])
grad formula: 2*(pred-target)/N = tensor([-0.2500,  0.2500,  0.1000, -0.4000])


## 2.9 Мини-тренировка: линейная регрессия на синтетике

Собираем всё вместе: создаём синтетический датасет y = 2*x + 1 + шум и обучаем линейную модель.

In [13]:
# Мини-тренировка: линейная регрессия y = 2*x + 1 + шум
# Собираем всё вместе: тензоры, autograd, функция потерь, оптимизатор
torch.manual_seed(42)
true_w, true_b = 2.0, 1.0  # истинные параметры
x = torch.randn(200, 1) * 2  # 200 точек, умножаем на 2 для разброса
y = true_w * x + true_b + torch.randn(200, 1) * 0.5  # добавляем шум

# Инициализируем параметры модели: вес w и смещение b
w = torch.randn(1, 1, requires_grad=True)  # требует градиенты для обновления
b = torch.zeros(1, requires_grad=True)
optimizer = torch.optim.SGD([w, b], lr=0.02)  # стохастический градиентный спуск

for epoch in range(200):
    y_pred = x @ w + b         # предсказание модели
    loss = F.mse_loss(y_pred, y)  # среднеквадратичная ошибка
    optimizer.zero_grad()      # обнуляем старые градиенты
    loss.backward()            # обратное распространение
    optimizer.step()           # шаг градиентного спуска

# Сравниваем истинные и обученные параметры
print(f"True: y = {true_w}x + {true_b}")
print(f"Learned: y = {w.item():.3f}x + {b.item():.3f}")
print(f"Loss (MSE): {loss.item():.4f}")

True: y = 2.0x + 1.0
Learned: y = 2.012x + 1.064
Loss (MSE): 0.2074


## Выводы

In [14]:
# Подводим итог: основы тензоров PyTorch освоены
print("=== Tensor fundamentals complete ===")
print("Topics covered:")
print("  - Tensor creation (from list, numpy, random, zeros, ones)")
print("  - Data types (dtype) and devices (device)")
print("  - Indexing, slicing, reshaping (view, reshape, transpose)")
print("  - Math operations and matrix multiplication")
print("  - Broadcasting")
print("  - Autograd: backward, gradients, detach, no_grad")
print("  - Loss functions and gradient computation")


=== Tensor fundamentals complete ===
Topics covered:
  - Tensor creation (from list, numpy, random, zeros, ones)
  - Data types (dtype) and devices (device)
  - Indexing, slicing, reshaping (view, reshape, transpose)
  - Math operations and matrix multiplication
  - Broadcasting
  - Autograd: backward, gradients, detach, no_grad
  - Loss functions and gradient computation
